name: Update Design Tokens

on:
  push:
    paths:
      - "tokens.json"  
  workflow_dispatch:  

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run fix-token script
        run: node fix-token.cjs

      - name: Run build script
        run: node build.cjs

      - name: Commit and push if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "anand-ceindia"
          git config --global user.email "itadmin@contentenablers.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update from tokens.json changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/contentenablers/sdx-figama-dictionary.git

      - name:  Trigger consumer repo
        run: |
            curl -X POST https://api.github.com/repos/contentenablers/ceui/dispatches \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -d '{"event_type":"tokens-updated"}'
